#!/bin/bash

GEMDIR=$1
PARENT=`pwd`

function del_mod_src
{
	read -r -p "Would you like to delete this module's source directory? [Y/n] " rsp
	case "$rsp" in
		[yY][eE][sS]|[yY])
			cd $PARENT
			rm -rf $GEMDIR
			;;
		*)
			;;
	esac
}

if [ ! -d $GEMDIR ]; then
	echo "Unknown directory: $GEMDIR"
	exit 1
fi

cd $GEMDIR

SPEC=0
GEM=0
README=0
if [ -f *.gemspec ]; then
	SPEC=1
fi

if [ -f *.gem ]; then
	GEM=1
else
	GEM=0
fi

if [[ $SPEC -eq 0 ]]; then
	echo "Missing gemspec"
	_ERROR=1
fi

if [[ $GEM -eq 1 ]]; then
	rm *.gem
fi

if [[ $_ERROR -eq 1 ]]; then
	echo "Errors encountered. Aborting"
	exit 1
fi

gem build *.gemspec

if [[ $? -ne 0 ]]; then
	echo "gem build failed."
	exit 1
else
	gem=`ls *.gem | awk -F'-' '{ print $1 }'`
	mv *.gem $gem.gem
	if [ -f $PARENT/modules/$gem.gem ]; then
		read -r -p "Module exists. Would you like to replace it? [Y/n] " response
		case "$response" in
			[yY][eE][sS]|[yY])
				del_mod_src
				exit 0
				;;
			*)
				echo "Module built, not added to Genesis"
				exit 0
				;;
		esac
	else
		echo "Module $gem added to Genesis"
		del_mod_src
	fi
fi
