#!/bin/bash

function template
{
	local _gem="$1"
	local gem="$_gem"
	local gem="$(tr '[:lower:]' '[:upper:]' <<< ${gem:0:1})${gem:1}"
	cat > $_gem/$_gem.html <<-EOF
<html>

<head>
	<title>Help - $gem</title>
	<link rel="icon" href="imgs/gecko.png" />
	<link rel="stylesheet" type="text/css" href="css/sunburst.css" />
	<link rel="stylesheet" type="text/css" href="css/style.css" />
	<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
</head>

<body>
	<div id="main" class="scrollable">
		<div class="content-wrapper">
			<div class="content">
				<div class="centered">
					<div class="contents">
						<h1>$gem</h1>
						<!-- Insert readme info here-->

						<!-- If you want to give a code example use:
						<pre class="prettyprint linenums">
code here</pre>
						-->
						<!-- If you want to use bullets:
						<ul class="info">
							<li>...</li>
							<li>...</li>
						</ul>
						-->
						<!-- nested bullets:
						<ul class="info">
							<li>...</li>
							<ul id="info2">
								<li>...</li>
							</ul>
							<li>...</li>
						</ul>
						-->
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
	EOF
}

if [[ "$1" == "" ]]; then
	echo "Usage: mkmod <modname>"
	exit 1
fi

if [ -d $1 ]; then
	echo "Module already exists. Aborting"
	exit 1
fi

mkdir -p $1/lib/

cat > $1/$1.gemspec <<EOF
Gem::Specification.new do |s|
	s.name = ''
	s.version = '0.0.0'
	s.summary = ""
	s.description = ""
	s.authors = [ "" ]
	s.email = ""
	s.files = [ "lib/" ]
	s.homepage = ""
	s.license = ''
end
EOF

cat > $1/lib/$1.rb <<-EOF
#!/bin/ruby

def mname
	"$1"
end

def cmds
	[ "generate" ]
end

def vars
	[ ]
end

def use
	[ ]
end

def generate(vhash)

end
EOF

echo "" > $1/gem.list
echo "" > $1/deb.list
template $1

echo "Module skeleton directory:$1 created"
echo "Please edit $1/$1.gemspec and add scripts and any dependencies in $1/lib/"
echo "List necessary gems in file $1/gem.list"
echo "List necessary deb pkgs (apt-get capable) in file $1/deb.list"
echo "Edit $1/$1.html to explain your module"
echo "Delete any unneccessary files"
echo "To pack your module into a gem and add it to genesis, run bgem $1"
